# name: Deploy to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.8.16'

#       - name: Create and activate virtual environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate

#       - name: Install dependencies
#         run: |
#           pip install numpy
#           pip install matplotlib
#           pip install basemap
#           pip install basemap-data-hires
#           pip install metpy
#           pip install pandas
#           pip install netcdf4
#           pip install mkdocs
#           pip install seaborn
#           pip install mkdocs-material
#           pip install pymdown-extensions
#           pip install mkdocstrings
#           pip install mkdocs-git-revision-date-plugin
#           pip install mkdocs-jupyter
#           pip install ipykernel


#       - name: Build MkDocs
#         run: mkdocs build

#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           personal_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./site
